In [167]:
ROOT_PATH = "/home/andreasideras/research_ideas/BankruptcyPredictionAD"
import sys
sys.path.append(ROOT_PATH) 

import pandas as pd
import numpy as np
import notebooks.utils as notebooks_utils
import warnings
warnings.filterwarnings('ignore')

# import importlib
importlib.reload(notebooks_utils)

In [2]:
fins, labels = notebooks_utils.load_data()

In [168]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins, labels, cols_perc=0.45, false_rows_perc=1, true_rows_perc=0.85)
notebooks_utils.test_predictors(fins.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 45.0% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 85.0% dense columns

There are 30 columns

label
False    1921
True       75
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.446411  0.051586
Average Precision    0.553845  0.118279
Recall at Precision  0.956051  0.023361

In [169]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins, labels, cols_perc=0.31, false_rows_perc=0.9, true_rows_perc=0.7)
notebooks_utils.test_predictors(fins.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 31.0% dense rows on the original dataset
Then:
Select only false rows that have more than 90.0% dense columns
Select only true rows that have more than 70.0% dense columns

There are 78 columns

label
False    749
True      86
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.626584  0.033667
Average Precision    0.643084  0.081238
Recall at Precision  0.897058  0.039762

Fill with data from finsim

In [ ]:
fins_finsim = notebooks_utils.expand_with_finsim(fins)
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins_finsim, labels, cols_perc=0.45, false_rows_perc=1, true_rows_perc=0.85)
notebooks_utils.test_predictors(fins_finsim.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

In [171]:
fins_copy = fins.copy()
finsim = pd.read_csv("../data/other/finsim_feats_overlap_ecl_ao.csv")

In [183]:
sec = fins.loc[sliced_index, sliced_columns]

In [ ]:
finsim.index = finsim['cik'].astype(str) + "__" + finsim['period_of_report']
finsim.drop(columns=['cik','period_of_report'],inplace=True)

In [184]:
sec

,ShareBasedCompensation,OtherComprehensiveIncomeLossNetOfTax,AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment,EarningsPerShareBasic,PaymentsForRepurchaseOfCommonStock,ComprehensiveIncomeNetOfTax,InterestExpense,Depreciation,PaymentsToAcquirePropertyPlantAndEquipment,UnrecognizedTaxBenefits,...,DeferredTaxAssetsValuationAllowance,CurrentIncomeTaxExpenseBenefit,OperatingLeasesFutureMinimumPaymentsDueInThreeYears,AllocatedShareBasedCompensationExpense,EarningsPerShareDiluted,EffectiveIncomeTaxRateContinuingOperations,DepreciationDepletionAndAmortization,NetIncomeLoss,OperatingLeasesFutureMinimumPaymentsDueInFourYears,CashAndCashEquivalentsPeriodIncreaseDecrease
uid,,,,,,,,,,,,,,,,,,,,,
2034__2018-06-30,7782000.0,4227000.0,1.269000e+07,-8.98,NaN,-311894000.0,20855000.0,2006000.0,5771000.0,NaN,...,7.741600e+07,NaN,1533000.0,NaN,-8.98,-0.080,NaN,-316121000.0,1216000.0,45194000.0
14195__2019-06-30,NaN,-40278000.0,8.092940e+08,-1.31,11937000.0,-94361000.0,29242000.0,59800000.0,52454000.0,6975000.0,...,NaN,4454000.0,14784000.0,NaN,-1.31,0.206,64200000.0,-54083000.0,10345000.0,-18876000.0
18172__2016-12-31,1154000.0,NaN,1.155370e+08,-3.72,NaN,-100100000.0,36422000.0,10252000.0,3499000.0,NaN,...,7.990800e+07,NaN,6295000.0,1154000.0,-3.72,0.023,16378000.0,-107982000.0,5545000.0,24524000.0
1498301__2019-08-03,11500000.0,-2800000.0,1.638400e+09,-66.98,NaN,-664200000.0,107000000.0,273400000.0,136500000.0,50300000.0,...,1.525000e+08,-12900000.0,325400000.0,NaN,-66.98,0.018,321100000.0,-661400000.0,242700000.0,89100000.0
31235__2010-12-31,21000000.0,-375000000.0,4.985000e+09,-2.56,0.0,NaN,149000000.0,318000000.0,149000000.0,245000000.0,...,2.335000e+09,NaN,33000000.0,NaN,-2.56,NaN,378000000.0,-687000000.0,25000000.0,-400000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1526520__2012-12-31,30102000.0,1841000.0,3.762600e+07,1.39,NaN,195910000.0,11381000.0,20000000.0,29000000.0,24000000.0,...,1.167700e+07,92347000.0,3124000.0,30102000.0,1.37,NaN,NaN,194069000.0,1279000.0,184000000.0
1142596__2016-12-31,26924000.0,1481000.0,2.231650e+08,0.74,24734000.0,38628000.0,NaN,57100000.0,88372000.0,23322000.0,...,1.054400e+07,-11204000.0,9048000.0,26924000.0,0.69,NaN,102713000.0,37147000.0,8662000.0,-38696000.0
1142596__2017-12-31,22391000.0,3698000.0,2.772460e+08,1.63,11860000.0,86704000.0,NaN,69500000.0,110221000.0,25356000.0,...,1.624700e+07,9541000.0,12431000.0,NaN,1.50,NaN,121176000.0,83006000.0,10847000.0,-80840000.0
1590714__2016-12-31,NaN,213600000.0,1.204000e+08,-0.17,NaN,137900000.0,NaN,75000000.0,56300000.0,128300000.0,...,3.833000e+08,86000000.0,13900000.0,7300000.0,-0.65,-0.595,342300000.0,-73700000.0,10500000.0,-9600000.0
1590714__2017-12-31,NaN,256100000.0,8.980000e+07,-1.04,0.0,-43800000.0,NaN,78300000.0,59400000.0,90300000.0,...,3.917000e+08,133200000.0,19600000.0,11800000.0,-1.04,-0.023,354200000.0,-296200000.0,13900000.0,55200000.0