In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
ROOT_PATH = ""
import sys
sys.path.append(ROOT_PATH) 
from tqdm import tqdm
import pandas as pd
import numpy as np
import notebooks.utils as notebooks_utils
import warnings
warnings.filterwarnings('ignore')

/tmp/ipykernel_1858326/2630656791.py:5: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
fins, labels = notebooks_utils.load_data()

In [4]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins, labels, cols_perc=0.45, false_rows_perc=1, true_rows_perc=0.85)
notebooks_utils.test_predictors(fins.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 45.0% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 85.0% dense columns

There are 30 columns

label
False    1921
True       75
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.445042  0.095362
Average Precision    0.543961  0.165371
Recall at Precision  0.476786  0.151744

In [5]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins, labels, cols_perc=0.31, false_rows_perc=0.9, true_rows_perc=0.7)
notebooks_utils.test_predictors(fins.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 31.0% dense rows on the original dataset
Then:
Select only false rows that have more than 90.0% dense columns
Select only true rows that have more than 70.0% dense columns

There are 78 columns

label
False    749
True      86
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.575877  0.078962
Average Precision    0.632761  0.136898
Recall at Precision  0.544444  0.142968

Fill with data from finsim

In [6]:
sec2finsim, sec_filled = notebooks_utils.expand_with_finsim(fins,match_percentage=0.005,top=100)

Number of column pairs with matching values: 0
0 new values from finsim!

In [7]:
sorted_cols = sec_filled[list(sec2finsim.keys())].isna().mean().sort_values().index # finsim[list(sec2finsim.values())].isna().mean().sort_values().index#
for col_index, col in enumerate(sorted_cols):
    subset = sec_filled[sorted_cols[:col_index + 1]].dropna()
    print(col_index + 1, subset.shape)

In [8]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(sec_filled, labels, cols_perc=0.45, false_rows_perc=0, true_rows_perc=0)
notebooks_utils.test_predictors(sec_filled.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 45.0% dense rows on the original dataset
Then:
Select only false rows that have more than 0% dense columns
Select only true rows that have more than 0% dense columns

There are 30 columns

label
False    56908
True       258
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.021107  0.002758
Average Precision    0.038576  0.015740
Recall at Precision  0.073538  0.055537

In [9]:
sec_filled.loc[sliced_index,sliced_columns][labels.loc[sliced_index]].isna().mean(0).sort_values()

Assets                                                                      0.279070
LiabilitiesAndStockholdersEquity                                            0.282946
CashAndCashEquivalentsAtCarryingValue                                       0.286822
IncomeTaxExpenseBenefit                                                     0.302326
RetainedEarningsAccumulatedDeficit                                          0.325581
PropertyPlantAndEquipmentNet                                                0.329457
NetIncomeLoss                                                               0.356589
StockholdersEquity                                                          0.360465
OperatingIncomeLoss                                                         0.372093
ShareBasedCompensation                                                      0.387597
DeferredIncomeTaxExpenseBenefit                                             0.403101
CommonStockParOrStatedValuePerShare                                         0.406977
CommonStockSharesAuthorized                                                 0.410853
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    0.410853
CommonStockValue                                                            0.414729
NetCashProvidedByUsedInInvestingActivities                                  0.418605
NetCashProvidedByUsedInOperatingActivities                                  0.422481
NetCashProvidedByUsedInFinancingActivities                                  0.434109
CommonStockSharesIssued                                                     0.441860
InterestExpense                                                             0.461240
Liabilities                                                                 0.480620
WeightedAverageNumberOfSharesOutstandingBasic                               0.492248
WeightedAverageNumberOfDilutedSharesOutstanding                             0.500000
EarningsPerShareBasic                                                       0.500000
EarningsPerShareDiluted                                                     0.515504
ComprehensiveIncomeNetOfTax                                                 0.527132
AccumulatedOtherComprehensiveIncomeLossNetOfTax                             0.538760
CashAndCashEquivalentsPeriodIncreaseDecrease                                0.538760
PaymentsToAcquirePropertyPlantAndEquipment                                  0.554264
CurrentFederalTaxExpenseBenefit                                             0.562016
dtype: float64

In [10]:
sec_filled.loc[sliced_index,sliced_columns][~labels.loc[sliced_index]].isna().mean(0).sort_values()

CashAndCashEquivalentsAtCarryingValue                                       0.364501
IncomeTaxExpenseBenefit                                                     0.390015
StockholdersEquity                                                          0.404319
Assets                                                                      0.406850
LiabilitiesAndStockholdersEquity                                            0.411120
NetIncomeLoss                                                               0.417094
NetCashProvidedByUsedInFinancingActivities                                  0.439130
NetCashProvidedByUsedInInvestingActivities                                  0.439200
NetCashProvidedByUsedInOperatingActivities                                  0.440659
EarningsPerShareBasic                                                       0.447002
RetainedEarningsAccumulatedDeficit                                          0.447916
WeightedAverageNumberOfSharesOutstandingBasic                               0.451448
EarningsPerShareDiluted                                                     0.452819
DeferredIncomeTaxExpenseBenefit                                             0.453855
WeightedAverageNumberOfDilutedSharesOutstanding                             0.457282
ComprehensiveIncomeNetOfTax                                                 0.471586
PropertyPlantAndEquipmentNet                                                0.474749
AccumulatedOtherComprehensiveIncomeLossNetOfTax                             0.481127
ShareBasedCompensation                                                      0.481532
CommonStockSharesAuthorized                                                 0.499209
InterestExpense                                                             0.510438
CommonStockValue                                                            0.524250
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    0.525199
CommonStockSharesIssued                                                     0.526323
CashAndCashEquivalentsPeriodIncreaseDecrease                                0.528643
CommonStockParOrStatedValuePerShare                                         0.537763
PaymentsToAcquirePropertyPlantAndEquipment                                  0.538413
CurrentFederalTaxExpenseBenefit                                             0.541277
OperatingIncomeLoss                                                         0.546092
Liabilities                                                                 0.546953
dtype: float64

In [11]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(sec_filled, labels, cols_perc=0.31, false_rows_perc=0.9, true_rows_perc=0.7)
notebooks_utils.test_predictors(sec_filled.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 31.0% dense rows on the original dataset
Then:
Select only false rows that have more than 90.0% dense columns
Select only true rows that have more than 70.0% dense columns

There are 78 columns

label
False    749
True      86
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.575877  0.078962
Average Precision    0.632761  0.136898
Recall at Precision  0.544444  0.142968