In [1]:
%load_ext autoreload
%autoreload 2

import os
ROOT_PATH = os.path.join(os.getcwd(), os.pardir)
import sys
sys.path.append(ROOT_PATH) 
from tqdm import tqdm
import pandas as pd
import numpy as np
import notebooks.utils as notebooks_utils
import warnings
warnings.filterwarnings('ignore')

/tmp/ipykernel_3033094/1868342380.py:9: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
fins, labels = notebooks_utils.load_data()

In [28]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins, labels, cols_perc=0.45, false_rows_perc=1, true_rows_perc=0.85)
notebooks_utils.test_predictors(fins.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 45.0% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 85.0% dense columns

There are 30 columns

label
False    1921
True       75
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.445042  0.095362
Average Precision    0.543961  0.165371
Recall at Precision  0.476786  0.151744

In [19]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins, labels, cols_perc=0.31, false_rows_perc=0.9, true_rows_perc=0.7)
notebooks_utils.test_predictors(fins.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 31.0% dense rows on the original dataset
Then:
Select only false rows that have more than 90.0% dense columns
Select only true rows that have more than 70.0% dense columns

There are 78 columns

label
False    749
True      86
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.575877  0.078962
Average Precision    0.632761  0.136898
Recall at Precision  0.544444  0.142968

Fill with data from finsim

In [12]:
sec2finsim, sec_filled = notebooks_utils.expand_with_finsim(fins,match_percentage=0.001,top=20)

516054 new values from finsim!

In [41]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(sec_filled, labels, cols_perc=0.45, false_rows_perc=1, true_rows_perc=0.85)
notebooks_utils.test_predictors(sec_filled.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 45.0% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 85.0% dense columns

There are 33 columns

label
False    4727
True       68
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.213722  0.038747
Average Precision    0.297338  0.077618
Recall at Precision  0.280952  0.089595

Future Internet paper data

In [70]:
fi = pd.read_csv('/home/andreasideras/research_ideas/BankruptcyPredictionAD/data/future_internet_paper/future_internet_fins.csv')
fi.set_index('uid', inplace=True)
print(fi.label.value_counts())
print(fi.label.sum()/fi.shape[0])
notebooks_utils.test_predictors(fi.iloc[:,:-1], fi.iloc[:,-1], num_runs=10)

label
False    13425
True       196
Name: count, dtype: int64
0.014389545554658248

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.107830  0.005965
Average Precision    0.164516  0.047717
Recall at Precision  0.173421  0.094396