In [ ]:
ROOT_PATH = ""
import sys
sys.path.append(ROOT_PATH) 
from tqdm import tqdm
import pandas as pd
import numpy as np
import notebooks.utils as notebooks_utils
import warnings
warnings.filterwarnings('ignore')

# import importlib
# importlib.reload(notebooks_utils)

In [3]:
fins, labels = notebooks_utils.load_data()

In [4]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins, labels, cols_perc=0.45, false_rows_perc=1, true_rows_perc=0.85)
notebooks_utils.test_predictors(fins.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 45.0% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 85.0% dense columns

There are 30 columns

label
False    1921
True       75
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.446411  0.051586
Average Precision    0.553845  0.118279
Recall at Precision  0.956051  0.023361

In [5]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins, labels, cols_perc=0.31, false_rows_perc=0.9, true_rows_perc=0.7)
notebooks_utils.test_predictors(fins.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 31.0% dense rows on the original dataset
Then:
Select only false rows that have more than 90.0% dense columns
Select only true rows that have more than 70.0% dense columns

There are 78 columns

label
False    749
True      86
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.626584  0.033667
Average Precision    0.643084  0.081238
Recall at Precision  0.897058  0.039762

Fill with data from finsim

In [6]:
finsim = pd.read_csv("../data/other/finsim_feats_overlap_ecl_ao.csv")
finsim.index = finsim['cik'].astype(
    str) + "__" + finsim['period_of_report']
finsim.drop(columns=['cik', 'period_of_report'], inplace=True)

In [ ]:
sec2finsim, sec_filled = notebooks_utils.expand_with_finsim(fins,match_percentage=0.005,top=5)

Number of column pairs with matching values: 43
Columns ('Revenue', 'Revenues') have 5989 matching rows
Columns ('Gross Profit', 'GrossProfit') have 5580 matching rows
Columns ('Depreciation & Amortization', 'OtherDepreciationAndAmortization') have 164 matching rows
Columns ('Depreciation & Amortization', 'DepreciationAndAmortization') have 3282 matching rows
Columns ('Depreciation & Amortization', 'Depreciation') have 661 matching rows
Columns ('Depreciation & Amortization', 'DepreciationDepletionAndAmortization') have 7660 matching rows
Columns ('Operating Income (Loss)', 'OperatingIncomeLoss') have 5065 matching rows
Columns ('Non-Operating Income (Loss)', 'NonoperatingIncomeExpense') have 2360 matching rows
Columns ('Non-Operating Income (Loss)', 'OtherNonoperatingIncomeExpense') have 472 matching rows
Columns ('Interest Expense, Net', 'InterestRevenueExpenseNet') have 161 matching rows
Columns ('Interest Expense, Net', 'InterestIncomeExpenseNet') have 1455 matching rows
Columns ('Pretax Income (Loss), Adj.', 'NetIncomeLoss') have 132 matching rows
Columns ('Pretax Income (Loss)', 'ProfitLoss') have 300 matching rows
Columns ('Pretax Income (Loss)', 'NetIncomeLoss') have 249 matching rows
Columns ('Income (Loss) from Continuing Operations', 'IncomeLossFromContinuingOperations') have 1635 matching rows
Columns ('Net Income', 'NetIncomeLoss') have 12214 matching rows
Columns ('Net Income (Common)', 'NetIncomeLoss') have 11348 matching rows
Columns ('Cash, Cash Equivalents & Short Term Investments', 'CashAndCashEquivalentsFairValueDisclosure') have 207 matching rows
Columns ('Cash, Cash Equivalents & Short Term Investments', 'CashCashEquivalentsAndShortTermInvestments') have 378 matching rows
Columns ('Cash, Cash Equivalents & Short Term Investments', 'CashAndCashEquivalentsAtCarryingValue') have 9226 matching rows
Columns ('Accounts & Notes Receivable', 'AccountsReceivableNet') have 581 matching rows
Columns ('Accounts & Notes Receivable', 'AccountsAndNotesReceivableNet') have 146 matching rows
Columns ('Inventories', 'InventoryGross') have 108 matching rows
Columns ('Inventories', 'InventoryNet') have 8549 matching rows
Columns ('Property, Plant & Equipment, Net', 'PropertyPlantAndEquipmentNet') have 10609 matching rows
Columns ('Long Term Investments & Receivables', 'LongTermInvestmentsAndReceivablesNet') have 111 matching rows
Columns ('Long Term Investments & Receivables', 'LongTermInvestments') have 1114 matching rows
Columns ('Other Long Term Assets', 'OtherAssets') have 144 matching rows
Columns ('Total Noncurrent Assets', 'AssetsNoncurrent') have 580 matching rows
Columns ('Total Noncurrent Assets', 'NoncurrentAssets') have 234 matching rows
Columns ('Total Assets', 'Assets') have 13456 matching rows
Columns ('Short Term Debt', 'SecuredDebt') have 101 matching rows
Columns ('Long Term Debt', 'LongTermDebt') have 1053 matching rows
Columns ('Total Liabilities', 'Liabilities') have 9384 matching rows
Columns ('Share Capital & Additional Paid-In Capital', 'CommonStocksIncludingAdditionalPaidInCapital') have 253 matching rows
Columns ('Share Capital & Additional Paid-In Capital', 'AdditionalPaidInCapital') have 352 matching rows
Columns ('Treasury Stock', 'TreasuryStockValue') have 132 matching rows
Columns ('Net Income/Starting Line', 'NetIncomeLoss') have 6975 matching rows
Columns ('Net Cash from Operating Activities', 'NetCashProvidedByUsedInOperatingActivities') have 11345 matching rows
Columns ('Net Cash from Investing Activities', 'NetCashProvidedByUsedInInvestingActivities') have 11549 matching rows
Columns ('Cash from (Repayment of) Debt', 'ProceedsFromRepaymentsOfDebt') have 118 matching rows
Columns ('Cash from (Repurchase of) Equity', 'PaymentsForRepurchaseOfCommonStock') have 240 matching rows
Columns ('Net Cash from Financing Activities', 'NetCashProvidedByUsedInFinancingActivities') have 11669 matching rows
312860 new values from finsim!

In [40]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(sec_filled, labels, cols_perc=0.45, false_rows_perc=1, true_rows_perc=0.85)
notebooks_utils.test_predictors(sec_filled.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 45.0% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 85.0% dense columns

There are 32 columns

label
False    2622
True       67
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.330739  0.041580
Average Precision    0.371160  0.062669
Recall at Precision  0.969987  0.021811

In [41]:
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(sec_filled, labels, cols_perc=0.31, false_rows_perc=0.9, true_rows_perc=0.7)
notebooks_utils.test_predictors(sec_filled.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 31.0% dense rows on the original dataset
Then:
Select only false rows that have more than 90.0% dense columns
Select only true rows that have more than 70.0% dense columns

There are 89 columns

label
False    1878
True       72
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.509061  0.054438
Average Precision    0.586391  0.149815
Recall at Precision  0.964276  0.021797