In [2]:
%load_ext autoreload
%autoreload 2

import os
ROOT_PATH = os.path.join(os.getcwd(), os.pardir)
import sys
sys.path.append(ROOT_PATH) 
import pandas as pd
import numpy as np
import notebooks.utils as notebooks_utils
import warnings
warnings.filterwarnings('ignore')

/tmp/ipykernel_4183033/3317619833.py:8: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [ ]:
#fins, labels = notebooks_utils.load_data(after_year=None)

In [85]:
fins2007, labels2007 = notebooks_utils.load_data(after_year=2007)
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins2007, labels2007, cols_perc=0.7, false_rows_perc=1, true_rows_perc=1)
notebooks_utils.test_predictors(fins2007.loc[sliced_index,sliced_columns], labels2007.loc[sliced_index], num_runs=10)

Initially, there are 258 positives
After 2007, there are 221 positives
Select only columns that have more than 70.0% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 100% dense columns

There are 19 columns

label
False    12846
True        39
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.070089  0.013490
Average Precision    0.104673  0.046757
Recall at Precision  0.100000  0.122474

In [ ]:
fins2010, labels2010 = notebooks_utils.load_data(after_year=2010)
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins2010, labels2010, cols_perc=0.70, false_rows_perc=1, true_rows_perc=0.85)
notebooks_utils.test_predictors(fins2010.loc[sliced_index,sliced_columns], labels2010.loc[sliced_index], num_runs=10)

Select only columns that have more than 70.0% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 85.0% dense columns

There are 33 columns

label
False    2275
True       56
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.293565  0.050495
Average Precision    0.358417  0.182019
Recall at Precision  0.336667  0.199694

In [ ]:
fins, labels = notebooks_utils.load_data(after_year=None)
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(fins, labels, cols_perc=0.453, false_rows_perc=1, true_rows_perc=1)
notebooks_utils.test_predictors(fins.loc[sliced_index,sliced_columns], labels.loc[sliced_index], num_runs=10)

Select only columns that have more than 45.300000000000004% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 100% dense columns

There are 30 columns

label
False    1921
True        7
Name: count, dtype: int64

In [87]:
new_fins,new_labels = notebooks_utils.maximize_positive_density(fins, labels, top_cols=15)
notebooks_utils.test_predictors(new_fins, new_labels, num_runs=5)

Index(['label', 'Assets', 'LiabilitiesAndStockholdersEquity',
       'CashAndCashEquivalentsAtCarryingValue', 'IncomeTaxExpenseBenefit',
       'RetainedEarningsAccumulatedDeficit', 'PropertyPlantAndEquipmentNet',
       'LiabilitiesCurrent', 'AssetsCurrent', 'NetIncomeLoss',
       'StockholdersEquity', 'OperatingIncomeLoss', 'ShareBasedCompensation',
       'DeferredIncomeTaxExpenseBenefit',
       'CommonStockParOrStatedValuePerShare', 'CommonStockSharesAuthorized'],
      dtype='object')
label
False    11580
True        69
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.064462  0.005758
Average Precision    0.129416  0.080041
Recall at Precision  0.142857  0.127775

Fill with data from finsim

In [89]:
sec2finsim, sec_filled = notebooks_utils.expand_with_finsim(fins,match_percentage=0.001,top=20)
new_fins,new_labels = notebooks_utils.maximize_positive_density(sec_filled, labels, top_cols=15)
notebooks_utils.test_predictors(new_fins, new_labels, num_runs=5)

516054 new values from finsim!
Index(['label', 'CashAndCashEquivalentsAtCarryingValue', 'Assets',
       'LiabilitiesAndStockholdersEquity', 'IncomeTaxExpenseBenefit',
       'PropertyPlantAndEquipmentNet', 'RetainedEarningsAccumulatedDeficit',
       'NetIncomeLoss', 'LiabilitiesCurrent', 'AssetsCurrent',
       'OperatingIncomeLoss', 'StockholdersEquity',
       'DeferredIncomeTaxExpenseBenefit', 'ShareBasedCompensation',
       'NetCashProvidedByUsedInInvestingActivities',
       'NetCashProvidedByUsedInOperatingActivities'],
      dtype='object')
label
False    16328
True        75
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.048565  0.003854
Average Precision    0.092753  0.032147
Recall at Precision  0.106667  0.090431

In [60]:
sec2finsim2010, sec_filled2010 = notebooks_utils.expand_with_finsim(fins2010,match_percentage=0.001,top=20)
sliced_index, sliced_columns = notebooks_utils.get_sliced_perc(sec_filled2010, labels2010, cols_perc=0.85, false_rows_perc=1, true_rows_perc=1)
notebooks_utils.test_predictors(sec_filled2010.loc[sliced_index,sliced_columns], labels2010.loc[sliced_index], num_runs=10)

487871 new values from finsim!
Select only columns that have more than 85.0% dense rows on the original dataset
Then:
Select only false rows that have more than 100% dense columns
Select only true rows that have more than 100% dense columns

There are 15 columns

label
False    17834
True        68
Name: count, dtype: int64

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.050890  0.010333
Average Precision    0.079354  0.037146
Recall at Precision  0.102381  0.092857

Future Internet paper data

In [70]:
fi = pd.read_csv('/home/andreasideras/research_ideas/BankruptcyPredictionAD/data/future_internet_paper/future_internet_fins.csv')
fi.set_index('uid', inplace=True)
print(fi.label.value_counts())
print(fi.label.sum()/fi.shape[0])
notebooks_utils.test_predictors(fi.iloc[:,:-1], fi.iloc[:,-1], num_runs=10)

label
False    13425
True       196
Name: count, dtype: int64
0.014389545554658248

Baseline - Logistic Regression:

                         Mean       Std
F1 Score             0.107830  0.005965
Average Precision    0.164516  0.047717
Recall at Precision  0.173421  0.094396